### ISSUE TITLE
No Sensors Shown on iOS App

### ISSUE THREAD

**Issue by bl1nkr1** [theengs/app#83]
**Describe the bug**
When using the paid Theengs app on iOS on an iPhone 14 Pro Max running iOS 16.4.1(a), the Theengs app does not show any Sensors on the Sensors tab even though Bluetooth permissions have been granted. 

**To Reproduce**
1. Open the Theengs app.
2. Tap on **Sensors** from the hamburger menu.
3. Tap **Launch Detection**
4. (No sensors show up)

**Expected behavior**
Sensors should be shown on the Sensors screen. 

**Screenshots**
![IMG_0752](https://github.com/theengs/app/assets/135071962/f0a0377e-b047-4cad-b70d-0816be6d4e99)

**Environment (please complete the following information):**
* iOS App Version: 1.3.1

**Additional context**
When tapping on **Device Browser**, I can scan for nearby BLE devices, one of which is a BlueCharms BC08 Beacon, which is listed as supported on the Theengs documentation. I can blacklist the sensor and whitelist it from this view, but no sensors show up at all on the Sensors list, no matter how many refreshes take place.

**Comment by DigiH** [comment]
Hi @bl1nkr1,

Did you tap on **lauch detection** to then scan and detect the relevant sensors to be added and displayed in the app?

But the BC08 Beacon is not supported in the mobile app, only in Theengs Decoder, but should be added to the app in an upcoming update.

**Comment by bl1nkr1** [comment]
Hi @DigiH - Yes, after tapping on **Launch Detection**, the magnifying glass starts a breathing animation, but nothing ever shows up. I've also tried using the **Search for new sensors** option within the hamburger menu, which triggers the same animation, but nothing shows up to select.

**Comment by DigiH** [comment]
Sorry, some crossover 😉 I just updated the above message with the info about the BC08.

**Comment by bl1nkr1** [comment]
Just saw your update - thank you @DigiH 😄 - hopefully, that might be the key. I'll keep an eye out for the upcoming release and try again at that time. Please feel free to close this issue for now if needed.

**Comment by DigiH** [comment]
Thanks, we'll are working on also including the BC08  and other Decoder compatible devices which are not yet in the App. Please keep an eye out for upcoming updates.

Closing a being worked on.

Thanks

**Comment by DigiH** [comment]
@bl1nkr1 

May I ask what your main use case would be with the BC08, mainly for the temperature and humidity, or also for the x/y/z/ acceleration values?

And which protocol have you got your BC08 set to? Please make sure it is the **KSensor** protocol, as this is the only one supported by Theengs for the BC beacons. When set to this protocol it should actually already be recognised by Theengs App with a generic property display view.

Let us know how you get on.

**Comment by bl1nkr1** [comment]
Hi @DigiH - I was mainly looking for a pocket-size way to test/validate BLE devices before putting them into production in Home Assistant via a BLE Gateway. 

For the BC08, I was looking to validate battery level, verify motion, and push button activation and review the UUID/Major/Minor values which I customized - I don’t believe it supports attributes like temperature and humidity. 

I checked the Blue Charm documentation, and the BC08 beacon doesn’t support the **KSensor** protocol as that requires a telemetry chip which the BC08 doesn’t appear to have... I currently have this set to iBeacon mode, which would explain not finding it as a generic device. 

My future additions will likely be the MiFlora devices which I believe are shown in the screenshot examples, but I had the BC08 on hand for another project.

**Comment by DigiH** [comment]
@bl1nkr1 as I don't have a BC08 myself I can only speak for others, who seem to get temperature (no humidity - my bad), x/y/z acceleration and bettery voltage. The renaming of the protocol to KSensor might have been a mistake on our side (we'll need to look into the naming), but I'm wondering which of the different protocols supported by the BC08 it was, which transmitted the above properties supported by our decoder. The push button is not included as a separate property, but as far as I know it can be set tht the beacon only transmits the above properties when the button is pressed, so as to be able to use that as a button press indication.

If you are aware of a separate button press broadcast please let us know, so that we can include it in a future update to the decoder.

With the UUID, major and minor you seem to have the iBeacon protocol active, which is not recognised by Teengs app, and likely won't be in the foreseeable future, as so many other devices, especially also with randomised MAC addresses, send out iBeacon broadcasts everywhere.

Which BLE Gateway are you using with Home Assistant? If it is our [Theengs Gateway (Add-On) ](https://github.com/theengs/gateway) it will already recognise iBeacon broadcasts, but it won't create any auto-discovered entries to HA, for the above iBeacon noise issue reason. It can be easily monitored through MQTT Explorer or such.

The MiFlora is already being supported by Theengs App, when you get them in the future.

**P.S.**: I just heard from a team mate that KSensor is selectable in the BlueCharm app as an optional broadcast protocol, and this is what we're decoding with temperature, x/y/z acceleration and voltage.
